### ISSUE TITLE
import fails ( Nuxt.js ) 

### ISSUE THREAD

**Issue by RUSHt** [arkokoley/pdfvuer#10]
I have not registered the Component, or used it in the <template>

import fails as follows:-

import pdf from 'pdfvuer' ( and import pdfvuer from 'pdfvuer' )

Build succeeds, but browser error 'Unexpected token <'  - vm.js:80:10 'Missing stack frames' createScript@80:10 ?

Peter

**Comment by RUSHt** [comment]
This was becase the Vue module was not compiled.

**Comment by frederic117** [comment]
how you proceed?
I got the same error...

**Comment by RUSHt** [comment]
I ended up just showing the PDF URL at an iFrame, and that seemed to work pretty well.

**Comment by frederic117** [comment]
ah ok not with this module...
The problem is in an iframe it doesn't work on mobile (especially android) did you manage to do something for that?

**Comment by RUSHt** [comment]
I didn't need to support mobile, but the way I would solve the issue with this module would be to git clone into you VueJS project, and then it should just build as part of your Vue build.

**Comment by halower** [comment]
how you proceed?
I got the same error...

@frederic117

**Comment by FelipeBohnertPaetzold** [comment]
In my case I added a plugin to register the component, and in *nuxt.config.js* I imported the plugin only in the client.

*plugins/pdf.js*
```js
import Vue from 'vue'
import Pdf from 'pdfvuer'

Vue.component('pdf-viewer', Pdf)
```

*nuxt.config.js*
```js
{
    plugins: [
        // ... another plugins
        { src: '@/plugins/pdf', mode: 'client' },
    ],
}
```

**Comment by santoshag** [comment]
@FelipeBohnertPaetzold 
I'm new to ssr. Can you please show how you are using pdf-viewer in your component?
