### ISSUE TITLE
Import Package Not Work

### ISSUE THREAD

**Issue by ra-heang** [arkokoley/pdfvuer#105]
**Is your feature request related to a problem? Please describe.**

I have an installed the package, but it's not work.
1- My usage
![DeepinScreenshot_select-area_20210831104757](https://user-images.githubusercontent.com/43458062/131438707-25506c7b-d997-4fc9-9290-1ad8e1ab97f7.png)
2- My result in console
![DeepinScreenshot_select-area_20210831104540](https://user-images.githubusercontent.com/43458062/131438593-170e49a9-8c2d-4b27-97f1-7a5eb93691ea.png)

Please, tell me.thanks
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arkokoley** [comment]
Newer versions do not have this problem. Anything above v1.8 would work fine.
