### ISSUE TITLE
The prop "scale" doesn't actually scale the PDF

### ISSUE THREAD

**Issue by coreycoburn** [arkokoley/pdfvuer#11]
I added the prop `scale` to my PDF but the actual PDF doesn't change and the internal data object of the pdfvuer component isn't changed.

```javascript
<Pdf
  :src="quote.pdf"
  :scale="1.5"
/> 
```

The `pdfViewer` object still returns the same thing whether I leave out the scale or change it to anything else...

```javascript
pdfViewer: {
  scale: 1.2095148501545492
}
```

Is there something I am doing wrong? Thanks!

**Comment by arkokoley** [comment]
@coreycoburn You are doing nothing wrong. It seems that it was a problem with my code. :worried: 

There is an override in the code which explicitly sets the scale for the pdf. 
https://github.com/arkokoley/pdfvuer/blob/0b6ea850f5d1eec0ed87258b62df97120d43dc10/src/Pdfvuer.vue#L186

This instead should have been: 
```js
      self.drawScaled(self.scale);
```

So the default behavior is to set the scale to match the container width which is set by specifying nothing or 'page-width'. Setting a number in the scale prop should explicitly set it at that scale. The above line will do that. I'm pushing in a new release containing #12  and a fix for this.

Thanks for raising this issue.
