### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by mpapado3** [arkokoley/pdfvuer#120]
Hi,

can we have lazy loading?
I need to load only the current page and on each page change to load the next / previous page.
I am going to handle big pdf files and don't want to load all pages at the beginning.

**Comment by arkokoley** [comment]
If the pdf is stream optimized, you can instantiate only one instance of pdfvuer and display just one page. Please refer to the basic example from the readme. 

You can then render buttons/controls to programmatically change the page by changing the "page" prop on pdfvuer.
