### ISSUE TITLE
pdfvuer@1.9.2" has unmet peer dependency "pdfjs-dist@2.5.207"

### ISSUE THREAD

**Issue by vibhanshu-koyaltechsolutions** [arkokoley/pdfvuer#122]
This warning nowadays getting on the browser.

DevTools failed to load source map: Could not load content for webpack:///node_modules/vuetify/lib/index.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

I guess pdfjs-dist did some update (latest v2.13.216) but pdfvuer v1.9.2 internally using pdfjs-dist@2.5.207.

**Comment by arkokoley** [comment]
Updated the pdfjs version to 2.14.305. Please try with v1.10.0
