### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by guilhermeaiolfi** [arkokoley/pdfvuer#2]
I get nothing from http://blog.koley.in/pdfvuer/ in both: chrome and firefox.

**Comment by arkokoley** [comment]
There was a CORS issue. I have rectified that. Please check now. Be sure to wait for 3-4 seconds. It takes that much time to download a file of interest.

**Comment by guilhermeaiolfi** [comment]
Worked. Thanks.

Em sex, 5 de out de 2018 17:57, Gaurav Koley <notifications@github.com>
escreveu:

**Comment by Sylk** [comment]
@arkokoley how did you rectify the CORS issue?
