### ISSUE TITLE
Console log warnings

### ISSUE THREAD

**Issue by tanderton** [arkokoley/pdfvuer#30]
When opening a pdf, I am receiving the following console messages.  Everything works though.

Deprecated API usage: PDFDocumentLoadingTask.then method, use the `promise` getter instead.

Deprecated API usage: getViewport is called with obsolete arguments.

**Comment by SPQRInc** [comment]
Facing the same problem - would be cool to get this solved :-)

**Comment by Fanatic17** [comment]
I have the same problem too
