### ISSUE TITLE
Render callback

### ISSUE THREAD

**Issue by justice47** [arkokoley/pdfvuer#35]
Is where any way to set callback function which will be fired when the pdf is rendered?

**Comment by justice47** [comment]
I've discover `@loading` event, which returns `false` then render of particular page is finished I suppose.
But how do I now which page is finished render?

**Comment by arkokoley** [comment]
@justice47, I want to understand your use case for a call back function. Since callbacks in vue are considered an anti-pattern, I'm not too keen on supporting it. Also, you can always a pass the page you want to render as a prop.
