### ISSUE TITLE
How to enable renderInteractiveForms?

### ISSUE THREAD

**Issue by binoysarker** [arkokoley/pdfvuer#37]
Hello sir, i have installed this package and it is loading the pdf file. But i can not understand 

1. the default look of pdf viewer with other options with black backgroud and dowload, sidebar is not showing.
2. How to enable renderInteractiveForms property to edit the pdf form.

**Comment by Fanatic17** [comment]
Hi, any news on this issue?

**Comment by arkokoley** [comment]
@binoysarker @Fanatic17 This package is meant as a extensible base for others to build their own customizable pdf viewers. This will provide only the bare bone viewer. Please look at the "Advanced example" in the readme for a somewhat complete example.
