### ISSUE TITLE
Cors origin error when open pdf from another server

### ISSUE THREAD

**Issue by harryandriyan** [arkokoley/pdfvuer#40]
Hello, 
is any param option to enable Allow cors origin, to handle load pdf from another server 

Thanks!

**Comment by mkaradeniz** [comment]
I just ran into this issue too. You can pass an object to `:src` and add credential options there.

For example:

```
{
  withCredentials: true,
  httpHeaders: {
    Cookie: YOUR_COOKIES,
  },
  url: 'https://example.com',
}
```

See `DocumentInitParameters` on [the PDFJS Docs](https://mozilla.github.io/pdf.js/api/draft/module-pdfjsLib.html) for available options.

**Comment by harryandriyan** [comment]
Okay @mkaradeniz thanks :tada:

**Comment by adesm** [comment]
@mkaradeniz its not work for me
