### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by lucaros97** [arkokoley/pdfvuer#43]
I'm using pdfvuer in a Laravel + Inertia.js + Vue.js app and I need it to work on IE11. After some tests and research i found that the problem is `pdfvuer`. When i've it imported it doesn't work while if i removed it works fine

Any suggestion?

**Comment by andrewo0** [comment]
Hi @lucaros97 i have the same issue it's because
`data () {` is not correct it's missing a : and some other things IE11 does not like.

@arkokoley i think it's a good idea to run ESLint to find all the issues that need to be fixed

**Comment by andrewo0** [comment]
these ar the warnings and errors i'm getting when running ESlint
`Pdfvuer.vue
    2:1   warning  Expected " " character, but found "\t" character                           vue/html-indent
    3:1   warning  Expected " " character, but found "\t" character                           vue/html-indent
    3:24  warning  'name' should be on a new line                                             vue/max-attributes-per-line
    3:38  warning  Expected a space before '/>', but not found                                vue/html-closing-bracket-spacing
    4:1   warning  Expected " " character, but found "\t" character                           vue/html-indent
    4:29  warning  'ref' should be on a new line                                              vue/max-attributes-per-line
    5:1   warning  Expected " " character, but found "\t" character                           vue/html-indent
    5:4   warning  Require self-closing on HTML elements (<div>)                              vue/html-self-closing
    5:21  warning  'class' should be on a new line                                            vue/max-attributes-per-line
    6:1   warning  Expected " " character, but found "\t" character                           vue/html-indent
    6:34  warning  '@resize' should be on a new line                                          vue/max-attributes-per-line
    6:55  warning  Expected a space before '/>', but not found                                vue/html-closing-bracket-spacing
    7:1   warning  Expected " " character, but found "\t" character                           vue/html-indent
    8:1   warning  Expected " " character, but found "\t" character                           vue/html-indent
   15:38  error    'PDFFindController' is defined but never used                              no-unused-vars
   18:7   error    'DEFAULT_SCALE_DELTA' is assigned a value but never used                   no-unused-vars
   19:7   error    'MIN_SCALE' is assigned a value but never used                             no-unused-vars
   20:7   error    'MAX_SCALE' is assigned a value but never used                             no-unused-vars
   21:7   error    'DEFAULT_SCALE_VALUE' is assigned a value but never used                   no-unused-vars
   22:7   error    'CSS_UNITS' is assigned a value but never used                             no-unused-vars
   80:2   warning  The "props" property should be above the "data" property on line 72        vue/order-in-components
  113:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs
  118:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs
  140:8   error    'pageHeightScale' is assigned a value but never used                       no-unused-vars
  155:25  error    'size' is defined but never used                                           no-unused-vars
  162:2   warning  The "mounted" property should be above the "methods" property on line 132  vue/order-in-components
  169:7   error    'SEARCH_FOR' is assigned a value but never used                            no-unused-vars
  205:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs
  207:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs
  209:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs
  210:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs
  211:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs
  212:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs
  213:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs
  214:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs
  215:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs
  216:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs
  217:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs
  219:2   error    Mixed spaces and tabs                                                      no-mixed-spaces-and-tabs

✖ 39 problems (23 errors, 16 warnings)
  0 errors and 16 warnings potentially fixable with the `--fix` option.`

**Comment by andrewo0** [comment]
@lucaros97 take a look at this PR
https://github.com/arkokoley/pdfvuer/pull/44

**Comment by arkokoley** [comment]
Fixed in #44
