### ISSUE TITLE
Hyperlinks are not working

### ISSUE THREAD

**Issue by Mr-Nicolai** [arkokoley/pdfvuer#50]
Hello there,

when i have some hyperlinks in my PDF i can't click on them. Is there a way to enable this?

@arkokoley

**Comment by songispm** [comment]
Me too, how to solve it, seen you closed it.

**Comment by Mr-Nicolai** [comment]
Just set the annotation attribute. Then you can add annotations in your PDF (e. g. Hyperlinks) @songispm
![annotation](https://user-images.githubusercontent.com/38925535/81934369-26dd9680-95ef-11ea-91da-5860f01c92d2.PNG)
