### ISSUE TITLE
I found another project exactly similar to this. Which is the original??

### ISSUE THREAD

**Issue by SapneshNaik** [arkokoley/pdfvuer#54]
Here:

You both have the exact same readme too.

## https://github.com/FranckFreiburger/vue-pdf

**Comment by SapneshNaik** [comment]
Just checked out the commit history on the linked project. Seems like that is the original project. May I ask what additions have you made if you have forked the original?

**Comment by arkokoley** [comment]
This project is not a fork of vue-pdf. I had earlier used vue-pdf for a project of mine but found it lacking of a few features for my use case. Over time, vue-pdf has also incorporate the changes that I made in pdfvuer. These changes primarily included exposing the pdf's text layer, annotation layer and a loading event. Annotations are still missing from vue-pdf AFAIK.
