### ISSUE TITLE
pdf_viewer.js?968b:2403 TextLayerBuilder._bindEvents: `this.cancel()` should have been called when the page was reset, or rendering cancelled.

### ISSUE THREAD

**Issue by shijiezhou1** [arkokoley/pdfvuer#58]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
pdf_viewer.js?968b:2403 TextLayerBuilder._bindEvents: `this.cancel()` should have been called when the page was reset, or rendering cancelled.

**Describe alternatives you've considered**
I tried to fix and nothing works.

**Additional context**

**Comment by ViavaCos** [comment]
@shijiezhou1 

Hello, I meet same issue.
Hava you already solved this problem?

**Comment by shijiezhou1** [comment]
> @shijiezhou1
> 
> Hello, I meet same issue. Hava you already solved this problem?

 Not yet. I gave up and use iframe instead
