### ISSUE TITLE
warning after import pdfvuer: invalide MIME Type text/html

### ISSUE THREAD

**Issue by BenoitDesrosiers** [arkokoley/pdfvuer#59]
Using Laravel and VUE, when I import pdfvuer I get this error in the navigator:

`The script from “http://localhost:8000/d5e78dccb47e8995549b.worker.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.`
and then a syntax error
`SyntaxError: expected expression, got '<'`

and the pdf won't display. 

I tried with a fresh Laravel project and it works fine. So it must be a conflict with another package. 

this is my package-lock.json
[package-lock.json.txt](https://github.com/arkokoley/pdfvuer/files/4580946/package-lock.json.txt)

and my composer
[composer.lock.txt](https://github.com/arkokoley/pdfvuer/files/4580968/composer.lock.txt)

**Comment by arkokoley** [comment]
You might have had multiple instances of webpack runnning. Try this out: 
`lsof -i :8080 -S` get the PID and then `kill -9 PID` and restart your webpack process.
