### ISSUE TITLE
After npm upgrade getting this build error

### ISSUE THREAD

**Issue by hchandra2019** [arkokoley/pdfvuer#63]
Node Version : v12.18.1
NPM Version : 6.14.5

On building getting following error -
```
ERROR in ./node_modules/pdfjs-dist/webpack.js
Module not found: Error: Can't resolve 'worker-loader' in '/Users/hchandra/work/aom-laravel-v4/node_modules/pdfjs-dist'
 @ ./node_modules/pdfjs-dist/webpack.js 27:18-64
 @ ./node_modules/vue-loader/lib??vue-loader-options!./node_modules/pdfvuer/src/Pdfvuer.vue?vue&type=script&lang=js&
 @ ./node_modules/pdfvuer/src/Pdfvuer.vue?vue&type=script&lang=js&
 @ ./node_modules/pdfvuer/src/Pdfvuer.vue
```

This started happening after I upgraded my node version. I have tried installing external dependencies by myself such worker-loader or even the fs, but no luck. 

On further digging into the source, I found out that Pdfvuer.vue is importing   
`import pdfjsLib from 'pdfjs-dist/webpack.js'; `
If I import 
`import pdfjsLib from 'pdfjs-dist;` 
and then manually assign  worker 
`pdfjsLib.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';` it just works

Could you please check and let me know?
I believe the dependencies of requiring worker loader by PDF JS is breaking the build.

**Comment by arkokoley** [comment]
This was fixed by @aym3nb in #62. Please try version v1.6.1.

**Comment by arkokoley** [comment]
I overhauled the entire codebase.. and now distribute esm and commonjs files. Please upgrade to v1. 7.1 to see if that fixes your issue.

**Comment by pixelpaulaus** [comment]
i too seem to be getting worker file errors now. They don't seem to be built when i build the package. I have upgraded to 1.7.1
