### ISSUE TITLE
How to dinamically change the pdf sources?

### ISSUE THREAD

**Issue by juan-carvajal** [arkokoley/pdfvuer#64]
Hi, I tried using the packageto swith several pdf that come from a remote url, I only want to load each pdf once, and only when the user request it, I also want to be able to swith between any loaded pdf or unloaded pdf. I tried storing the promises in vue data props, but the pdf component only renders once, then theloading tasks are performed, but after they are cached, the pdf is stuck in the last document that was loaded through the creatingLoadingTask. how do I force the reload with the latest source?

**Comment by arkokoley** [comment]
Use a :key in the pdfvuer component and change the key when you change the src. This will force the component to be re-rendered.
