### ISSUE TITLE
Open annotated links in another tab

### ISSUE THREAD

**Issue by santoshag** [arkokoley/pdfvuer#66]
PDFLinkService can be configured to open links in another tab, however I'm not able to do it. Anyone able to achieve this? 
some context: https://github.com/mozilla/pdf.js/issues/7779 and https://stackoverflow.com/questions/33813373/how-to-open-hyperlinks-in-a-new-tab-window

This is what I tried:
```   
 var pdfLinkService = new PDFLinkService({
      externalLinkTarget: 2
    });
```

**Comment by arkokoley** [comment]
@santoshag  published as part of v1.8.1
