### ISSUE TITLE
Can't resolve 'fs'

### ISSUE THREAD

**Issue by haydenbech** [arkokoley/pdfvuer#71]
I'm trying to get the advanced example working. When I run npm run dev I get the following error:

```
ERROR in ./node_modules/pdfvuer/dist/pdfvuer.esm.js
Module not found: Error: Can't resolve 'fs' in '/home/vagrant/choirconcierge/node_modules/pdfvuer/dist'
 @ ./node_modules/pdfvuer/dist/pdfvuer.esm.js 2:0-20 79103:11-13
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/babel-loader/lib??ref--5-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/components/PDFViewer.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/components/PDFViewer.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/components/PDFViewer.vue
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
```

**Comment by aschaeffer** [comment]
Try to add in package.json:

```json
"browser": {
  "fs": false
}
```

**Comment by haydenbech** [comment]
> Try to add in package.json:
> 
> ```json
> "browser": {
>   "fs": false
> }
> ```
No change :(

**Comment by andrewo0** [comment]
just install fs `npm install --save fs`

**Comment by leo91000** [comment]
Same problem here, it seem pdfvuer.esm.js is requiring fs, which does not exists in browser

**Comment by andrewo0** [comment]
Hi i will submit a pr this weekend if i have some free time to fix some issues

**Comment by ahoiroman** [comment]
Got the same problem here. Would be happy to see your pr. If I can help with a coffee, let me know :-)

**Comment by trolikua** [comment]
> > Try to add in package.json:
> > ```json
> > "browser": {
> >   "fs": false
> > }
> > ```
> 
> No change :(

Try to add the code below to the webpack config file, it works for me.
```
    node: {
        fs: 'empty'
    }
```
