### ISSUE TITLE
Deprecated API usage: No "GlobalWorkerOptions.workerSrc" specified.

### ISSUE THREAD

**Issue by wbazalea** [arkokoley/pdfvuer#78]
I'm getting this error after updating the package:

GET http://localhost:8080/7.worker.js net::ERR_ABORTED 404 (Not Found)
Uncaught (in promise) Error: Setting up fake worker failed: "Cannot load script at: http://localhost:8080/7.worker.js".

@arkokoley

**Comment by vaidd4** [comment]
This comment on the related PDF.js issue might be useful
https://github.com/mozilla/pdf.js/issues/10478#issuecomment-518673665

**Comment by arkokoley** [comment]
Assuming you are using webpack to build your vue system: 

add worker-loader

```
npm i --save worker-loader
```

Add this to your webpack.config.js

```JS
module.exports = {
  module: {
    rules: [
      {
        test: /\.worker\.js$/,
        use: {
          loader: 'worker-loader',
          options: {
            filename: '7.worker.js'
          }
        }
      },
     ...
  ]
}
```
