### ISSUE TITLE
Unable to npm run build because '/Pdfvuer.vue: Support for the experimental syntax 'dynamicImport' isn't currently enabled'. 

### ISSUE THREAD

**Issue by Dorothysun** [arkokoley/pdfvuer#8]
I am having trouble to use the pdfvuer library and when I do npm run build, i got '/Pdfvuer.vue: Support for the experimental syntax 'dynamicImport' isn't currently enabled' error. But I am sure I have it enabled in my package.json so really couldn't figure out why it won't build.'

**Comment by Dorothysun** [comment]
My .babelrc file look like the following:
{
  "presets": [
    ["env", { "modules": false }],
    "stage-3"
  ],
  "plugins": ["syntax-dynamic-import"]
}

**Comment by arkokoley** [comment]
@Dorothysun your `.babelrc` file looks identical to mine. So the problem would be somewhere in package.json or the node version itself. 

Can you share the devDependencies from your `package.json` ?

**Comment by arkokoley** [comment]
@Dorothysun do you still have this issue?

**Comment by Dorothysun** [comment]
Sorry about my late reply! I found another library and that one works for me so I was no longer trying to debug this. But thank you so much for your reply!

**Comment by arkokoley** [comment]
@Dorothysun no problem!
