### ISSUE TITLE
createLoadingTask returns promise instead of task

### ISSUE THREAD

**Issue by ocha** [arkokoley/pdfvuer#81]
createLoadingTask is returning `promise` instead of the task itself. That results in options not being set on loading task correctly. So `onProgress` and `onPassword` options dont do anything. 

https://github.com/arkokoley/pdfvuer/blob/4cb379c4b7d80bd75bc2a66698ab71e88d52a6a3/src/Pdfvuer.vue#L43

**Comment by arkokoley** [comment]
Fixed in https://www.npmjs.com/package/pdfvuer/v/1.7.5
