### ISSUE TITLE
How to preview a pdf file with authorization token enabled

### ISSUE THREAD

**Issue by lijiext** [arkokoley/pdfvuer#88]
My project need authorzation to access a pdf file, so how can I add the token header in pdfvuer?

**Comment by arkokoley** [comment]
@lijiext 

You can use the createLoadingTask to create a loader with your custom token headers.

Use this as an example:

```js
var parameter = {
  url: this.url,
  httpHeaders: { Authorization: `Bearer <Token>` },
  withCredentials: true,
}
this.loadingTask = pdfvuer.createLoadingTask(parameter);
```

And then the template piece can be:
```html
 <pdfvuer :src="loadingTask" ....
```
