### ISSUE TITLE
Is @vue/cli-plugin-pwa correctly a depencency?

### ISSUE THREAD

**Issue by grk** [arkokoley/pdfvuer#91]
I'm wondering if @vue/cli-plugin-pwa should be a dependency, or maybe it would make more sense as a devDependency (or if it is needed at all.

It was added in https://github.com/arkokoley/pdfvuer/commit/12aa09b125cdc11d5336615815110a926fc6b7ad

**Comment by arkokoley** [comment]
@grk you are right. It shouldn't be a dependency. I will remove it in the next release by tomorrow. Thanks for bringing to my notice.

**Comment by grk** [comment]
Thank you for such a quick response!

**Comment by arkokoley** [comment]
@grk published as part of v1.8.1

**Comment by grk** [comment]
Awesome, thank you!
