### ISSUE TITLE
Warning: Setting up fake worker.

### ISSUE THREAD

**Issue by mesqueeb** [arkokoley/pdfvuer#96]
I get
> Warning: Setting up fake worker.

in the console, and the PDF stays on just loading.

Using `"1.8.3"` same issue in:
- Google chrome
- Safari
- Firefox

on macOS

**Comment by mesqueeb** [comment]
I have reverted to `"1.7.5"` and now it works again. I will stay on this old version for now.

**Comment by adrianvanladrillano** [comment]
Not working on nuxt :(

**Comment by adrianvanladrillano** [comment]
> I have reverted to `"1.7.5"` and now it works again. I will stay on this old version for now.

Not working on nuxt :(

**Comment by adrianvanladrillano** [comment]
> > I have reverted to `"1.7.5"` and now it works again. I will stay on this old version for now.
> 
> Not working on nuxt :(

https://github.com/arkokoley/pdfvuer/issues/93#issuecomment-844583849 this fixed the issue

**Comment by adam91holt** [comment]
I'm also getting this error on any version I try. I have been trying for hours now. 

Tried the following so far

- Webpack config changes
- Using CDN to try and set GlobalWorkerOptions.workerSrc
- Using  ```import 'pdfjs-dist/build/pdf.worker.entry'```

These are the error I get in the console.
```
Deprecated API usage: No "GlobalWorkerOptions.workerSrc" specified.
Warning: Setting up fake worker.
Uncaught SyntaxError: Unexpected token '<'
```

I'm pretty sure it's related to webpack i'm using  "^4.43.0"

Thanks!

**Comment by arkokoley** [comment]
This should be fixed with [v1.9.1](https://www.npmjs.com/package/pdfvuer/v/1.9.1)

**Comment by mesqueeb** [comment]
@arkokoley fixed for me on 1.9.2!

**Comment by rzdev** [comment]
Hi @arkokoley, i'm on v2.0.1 & Vue 3 and the fake worker warning message came up in the console

**Comment by mssayari** [comment]
I also have this warning on Vue 3, but it's not like always. it only happens at first time using component.
